- src/components/atoms/article-content/article-content.scss
- src/components/atoms/article-content/article-content.stories.tsx
- src/components/atoms/article-content/article-content.test.tsx
- src/components/atoms/article-content/article-content.tsx
- src/components/atoms/article-content/mock-content.ts
- src/components/atoms/heading/heading.scss
- src/components/atoms/heading/heading.stories.tsx
- src/components/atoms/heading/heading.test.tsx
- src/components/atoms/heading/heading.tsx
- src/sass/_typography.scss
- src/types/content.ts
- src/utils/content-to-jsx.test.tsx
- src/utils/content-to-jsx.tsx
adding the ArticleContent component.
We will need to decide whether we want a separate component for each content type and where we will put styling.
> add article-content component and contentToJsx utility

- .dockerignore
- .github/workflows/ci.yaml
- Dockerfile
- Makefile
- README.md
- docker-compose.yaml
fixes #17 
fixes #18 
Start building images for deployments
> Add docker build system

- src/components/atoms/jump-to-menu/jump-to-menu.scss
- src/components/atoms/jump-to-menu/jump-to-menu.stories.tsx
- src/components/atoms/jump-to-menu/jump-to-menu.test.tsx
- src/components/atoms/jump-to-menu/jump-to-menu.tsx
- src/sass/_typography.scss
- add jump to menu
- add test
- lint fixes
> add jump to menu

- src/components/molecules/tabbed-navigation/index.ts
- src/components/molecules/tabbed-navigation/tab.test.tsx
- src/components/molecules/tabbed-navigation/tab.tsx
- src/components/molecules/tabbed-navigation/tabbed-navigation.scss
- src/components/molecules/tabbed-navigation/tabbed-navigation.stories.tsx
- src/components/molecules/tabbed-navigation/tabbed-navigation.test.tsx
- src/components/molecules/tabbed-navigation/tabbed-navigation.tsx
- fix just about working Tabbed navigation
- add test and styles
- lint fixes
> add tabbed navigation

- src/components/molecules/site-header/site-header.scss
Noted during importing more site styles that this is set twice, but slightly different use of settings. This PR Consolidates to the use similar to elsewhere
> Consolidate settings.border value

- src/components/atoms/editors-and-reviewers/editors-and-reviewers.module.scss
- src/components/atoms/editors-and-reviewers/editors-and-reviewers.stories.tsx
- src/components/atoms/editors-and-reviewers/editors-and-reviewers.test.tsx
- src/components/atoms/editors-and-reviewers/editors-and-reviewers.tsx
- src/sass/_typography.scss
References https://github.com/elifesciences/enhanced-preprints-client/issues/56
> Review components reviewers and editors

- src/components/pages/article/article-page.tsx
- src/manuscripts.ts
- src/pages/reviewed-preprints/[msid].page.tsx
To generate DOIs as we expect them to be minted
> Enable generation of elife doi from msid and version

- src/components/pages/article/article-page.stories.tsx
- src/components/pages/article/article-page.tsx
> fixes types in article page story

- docker-compose.yaml
- src/components/atoms/article-content/article-content.module.scss
- src/components/atoms/article-flag/article-flag.module.scss
- src/components/atoms/button/button.module.scss
- src/components/atoms/jump-to-menu/jump-to-menu.module.scss
- src/components/atoms/review-content/review-content.module.scss
- src/components/atoms/review-content/review-content.test.tsx
- src/components/atoms/review-content/review-content.tsx
- src/components/pages/article/article-page.module.scss
- src/components/pages/article/article-page.tsx
- src/pages/_document.page.tsx
- src/sass/_settings.scss
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/77
> Elife Assessment

- src/components/atoms/institutions/institutions.tsx
- src/components/molecules/content-header/content-header.stories.tsx
- src/components/molecules/content-header/content-header.test.tsx
- src/components/molecules/content-header/content-header.tsx
- src/components/pages/article/article-page.stories.tsx
- src/components/pages/article/article-page.tsx
- src/pages/reviewed-preprints/[msid].page.tsx
> Add institutions

- src/components/molecules/article-status/article-status.tsx
- src/components/pages/article/article-page.tsx
- Remove citations
- remove all buttons expect download
> Remove items not ready for launch

- src/manuscripts.ts
- src/utils/generate-image-url.ts
fixes #95 
Currently there isn't a docmap, so this will fail until that is created (https://staging.sciety.org/docmaps/v1/evaluations-by/elife/10.1101/2022.05.30.22275761.docmap.json)
> enable a new article with Maths in, and fix images to always serve the max size

- src/manuscripts.ts
- Adds timeline information for next set of reviewed preprints
- Revised status description inline with Chris' latest designs
- Timeline event name changed from `Peer review` to `Sent for peer review`
> Adds timeline events for more launch examples

- src/pages/index.page.tsx
I'm fed up of relying on history and my code editor to find msids
> Add a ridiculously simple index page

- Dockerfile
This means we can set env vars server-side, and the production run will contain the effects of them.
> Make sure a prod container rebuilds the production files on startup

- src/components/atoms/button/button.stories.tsx
- src/components/atoms/button/button.tsx
- src/components/molecules/article-status/article-status.stories.tsx
- src/components/molecules/article-status/article-status.tsx
- src/components/pages/article/article-page.stories.tsx
- src/components/pages/article/article-page.tsx
- src/manuscripts.ts
- src/pages/reviewed-preprints/[msid].page.tsx
Not all manuscripts have PDFs yet.
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/100
> Add PDFs and wireup through pages

- src/config.ts
- src/pages/_document.page.tsx
related https://github.com/elifesciences/enhanced-preprints-client/issues/104
> Add in support got GoogleTagManager with injected ID

- src/config.ts
- src/pages/_document.page.tsx
related to https://github.com/elifesciences/enhanced-preprints-client/issues/104
> Fix GTM and add cookiebot

- src/components/molecules/content-header/content-header.tsx
> deduplicate the inistitutions based on name and address

- src/manuscripts.ts
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/144
> Updated wording for article status text

- .storybook/preview-head.html
- src/components/atoms/review-content/review-content.module.scss
- src/pages/_document.page.tsx
by including weight 700 when loading the font
> Get some browsers to do a better job with rendering weight 600

- src/components/molecules/site-header/site-header.tsx
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/154
> Add nav secondary links

- src/components/atoms/review-content/review-content.test.tsx
- src/components/atoms/review-content/review-content.tsx
- src/components/molecules/tabbed-navigation/tabbed-navigation.stories.tsx
- src/components/molecules/tabbed-navigation/tabbed-navigation.test.tsx
- src/components/molecules/tabbed-navigation/tabbed-navigation.tsx
- src/components/pages/article/article-page.tsx
This moves the state hook to the page level so we can pass the setActiveTab function to the anchor in the eLife assesment box.
> peer review link in assesment fix

- src/components/pages/article/article-page.module.scss
- src/components/pages/article/article-page.tsx
> add menu spacer

- src/manuscripts.ts
> Remove unused manuscripts and stale preprint configs

- src/manuscripts.ts
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/172
> Add Reviewed Preprint posted to timeline events

- src/manuscripts.ts
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/167
> Add links to PDFs for remaining articles

- src/config.ts
- src/pages/reviewed-preprints/[msid].page.tsx
https://github.com/orgs/elifesciences/projects/11/views/4
> add cache to article route with an env var

- src/components/atoms/abstract/abstract.stories.tsx
- src/components/atoms/article-content/article-content.stories.tsx
- src/components/atoms/authors/authors.stories.tsx
- src/components/atoms/figure/figure.test.tsx
- src/components/atoms/reference-list/reference-list.stories.tsx
- src/components/atoms/reference-list/reference-list.test.tsx
- src/components/molecules/author-list/author-list.stories.tsx
- src/components/molecules/author-list/author-list.test.tsx
- src/components/molecules/content-header/content-header.stories.tsx
- src/components/pages/article/article-page.stories.tsx
- src/components/pages/article/article-page.test.tsx
- src/utils/mocks/authors.ts
- src/utils/mocks/content.ts
- src/utils/mocks/index.ts
- src/utils/mocks/meta-data.ts
- src/utils/mocks/peer-review.ts
- src/utils/mocks/references.ts
- src/utils/mocks/status.ts
(cherry picked from commit 2769093ccf581d25a609ce9d214ed4544361668b)
> add missing tests and centralise mock data

- .github/workflows/ci.yaml
fixes https://github.com/elifesciences/enhanced-preprints-server/issues/483
> Add production build to a PR test run

- Makefile
- README.md
- docker-compose.prod.yaml
- docker-compose.yaml
- better layout of dependent services and app specific ones
- add override example for running a production build
- fix issues with MongoDB GUI not starting and health check working before the MongoDB server is ready
- standardise the ports used by services
- update docs to not point towards react-create-app scripts, and point towards the various docker-compose workflows
- Remove storybook profile and include in main docker-compose run.
- Update Makefile with new targets, and update documentation
References https://github.com/elifesciences/enhanced-preprints-server/issues/486
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/208
> Make multiple changes to the docker-compose:

- src/components/molecules/content-header/content-header.tsx
- src/components/pages/article/article-page.stories.tsx
- src/components/pages/article/article-page.tsx
- src/pages/reviewed-preprints/[msid].page.tsx
- src/types/index.ts
- src/types/meta-data.ts
- src/types/peer-review.ts
- src/utils/json-fetch.ts
> Server response types

- renovate.json
fixes https://github.com/elifesciences/enhanced-preprints-client/issues/219
> Enable renovate on this repo

- src/components/layouts/default.module.scss
- src/components/layouts/default.stories.tsx
- src/components/layouts/default.tsx
- src/components/pages/article/article-page.module.scss
- src/components/pages/article/article-page.stories.tsx
- src/components/pages/article/article-page.tsx
- src/pages/_app.page.tsx
- src/pages/index.page.tsx
- Reduces white page flash between pages changes
- Reduces re-render time
- introduces a place for a global layout (and a footer, maybe?)
> Add a layout

- .storybook/fix-next-image.js
Fix issue with storybook complaining loudly when next/image isn't generating a servable image
> swap out nextjs image with <img> in storybook

- .github/workflows/build-preview.yaml
fixes https://github.com/elifesciences/enhanced-preprints-issues/issues/353
> Fix preview build CI and set deployment status correctly

- src/components/molecules/author-information-list/author-information-list.tsx
- src/config.ts
- add key in author information
- stop the config warning about nextjs level config
> fix test warnings

- src/components/molecules/site-header/site-header.tsx
relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/374
> Update Submit your research url in EPP

- src/components/molecules/site-header/site-header.scss
- src/components/molecules/site-header/site-header.tsx
site-header__logo_link was not being used until I put in the link
> add link to logo to homepage and remove unwanted padding

- src/components/atoms/socials/socials.tsx
- src/components/molecules/article-status/article-status.stories.tsx
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/491
> add url to doi passed into Socials and update story to match a doi

- .github/workflows/add-pdf-url-to-manuscript.yaml
See: https://github.com/actions/runner-images/issues/6002
> Switch to ubuntu 20.04 for github action

- src/components/atoms/review-content/review-content.test.tsx
- src/components/atoms/review-content/review-content.tsx
Message passed on by Siân that 'valuable' needs to be added to the list of controlled vocabulary. PR was provided to us so I picked up the change to get it through quickly.
> Added new controlled vocabulary word 'valuable'

- src/components/molecules/author-information-list/author-information-list.test.tsx
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/537
> refactor author-information-list test to use author mocks

- .storybook/main.js
Solution taken from: https://stackoverflow.com/questions/71158775/storybook-couldnt-resolve-fs
Not sure if it is all needed but working for me locally.
> Potential fix for Module not found: Can't resolve 'fs' in '/opt/epp-client/src'

- .github/workflows/publish-manuscript.yaml
- data/manuscripts.json
- manuscripts.json
- src/manuscripts.test.ts
- src/pages/api/reviewed-preprints.page.test.ts
- src/pages/api/reviewed-preprints.page.ts
- src/pages/reviewed-preprints/[msid]/index.page.tsx
- src/scripts/publishManuscript.test.ts
- src/scripts/publishManuscript.ts
- test-utils/data/example_manuscripts.json
- test-utils/data/manuscripts.json
@QueenKraken this was discussed this morning. Please approve, if you are happy.
> Change 'Reviewed Preprint posted' to 'Reviewed preprint posted'

- src/components/atoms/reference/reference.scss
> Refactor reference font size

- src/components/atoms/socials/socials.tsx
- src/config.ts
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/628
> Added via to the twitter url

- src/components/atoms/reference-list/reference-list.scss
- src/components/atoms/reference/reference.scss
- src/components/atoms/reference/reference.test.tsx
- src/components/atoms/reference/reference.tsx
- src/types/reference.ts
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/121
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/354
> References fixes

- src/components/pages/article/article-page.tsx
Temporary disable shallow links in epp client, relates to https://github.com/elifesciences/enhanced-preprints-issues/issues/690
> Try disable shallow links for now

- src/components/atoms/figure/figure.stories.tsx
- src/components/atoms/figure/figure.test.tsx
- src/components/atoms/figure/figure.tsx
- src/types/content.ts
https://elifesciences.org/reviewed-preprints/87406#s4e does not have a figure id.
After this is approved and merged in here is the corresponding change to server: https://github.com/elifesciences/enhanced-preprints-server/pull/729
> Figure id should be optional

- src/components/molecules/timeline/timeline.test.tsx
- src/components/molecules/timeline/timeline.tsx
- src/utils/mocks/authors.ts
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/641
> Adjusted date format and changed tests

- src/pages/_document.page.tsx
- src/utils/content-to-jsx.tsx
- WIP experimental fixes
- reinstate scroll margin
- fix merge conflict issue
> Fix browser jump incorrect behaviour by disabling smooth scrolling

- src/components/atoms/authors/authors.tsx
- src/components/atoms/citation/citation.test.tsx
- src/components/atoms/citation/citation.tsx
- src/components/molecules/article-status/article-status.tsx
- src/components/molecules/author-information-list/author-information-list.tsx
- src/components/molecules/modal/modal.stories.tsx
- src/pages/api/reviewed-preprints.page.ts
Updated the author name formatting across several components to handle potential undefined givenNames and familyNames. This supports better rendering of author information and prevents potential errors in displaying author data.
> feat: handle potential undefined author names

- src/config.ts
- src/pages/reviewed-preprints/[...path].page.tsx
Metadata should be given name then surname
> Reverse the order of author name in metadata

- src/pages/reviewed-preprints/[...path].page.tsx
- src/utils/format-author-name.ts
Also move the correct name formatting to a utility function and use as part of metadata
> Support honorific suffix in metadata name

- src/components/molecules/author-information-list/author-information-list.test.tsx
- src/utils/format-author-name.test.ts
- src/utils/format-author-name.ts
- src/utils/mocks/authors.ts
Also wrote a test for it this time
> Fix author name formatting

- src/pages/preview/[...path].page.tsx
- src/pages/reviewed-preprints/[...path].page.tsx
- src/utils/fetch-data.ts
- src/utils/json-fetch.ts
- Add jsonFetchOrNull function to handle null responses
- Add notFound return for non-existing article versions
- Refactor imports in various files for clarity and efficiency
This is a followup to: https://github.com/elifesciences/enhanced-preprints-server/pull/840
> feat: handle non-existing article versions

- src/types/content.ts
- src/utils/mocks/content.ts
- Made claimType optional in ClaimContent type
- Added a generic 'Claim' and a 'Statement' claim to the mocks
> feat: update ClaimContent type and mocks

- docker-compose.automated.yaml
The automation config doesn't load images into the correct place and use that in the image server. 
This change does both, and it seems to work fine.
> Fix automation so that we load the correct images from the correct place

- src/components/atoms/clipboard/clipboard.test.tsx
- src/pages/api/reviewed-preprints.page.test.ts
- src/scripts/cliPublishManuscript.ts
- src/types/article-status.ts
- src/utils/generate-article-status.test.ts
- src/utils/generate-article-status.ts
Addressing the following issue: https://github.com/elifesciences/enhanced-preprints-issues/issues/922
> Change 'Revised preprint' to 'Reviewed Preprint' for all article vs

- src/components/atoms/editors-and-reviewers/editors-and-reviewers.test.tsx
- src/components/atoms/editors-and-reviewers/editors-and-reviewers.tsx
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/935
> add function to convert roles to display friendly version

- src/pages/api/reviewed-preprints.page.test.ts
Closes https://github.com/elifesciences/enhanced-preprints-issues/issues/892
> fix broken ts in test

- src/components/molecules/timeline/timeline.stories.tsx
- src/components/molecules/timeline/timeline.test.tsx
- src/components/molecules/timeline/timeline.tsx
The current setup for the aria-label was not working and is over engineered. We only have to state it's just a timeline.
> Simplifying aria-label to just one label statement

- src/components/molecules/improved-timeline/improved-timeline.scss
Improved readability and maintainability of SCSS for the 'improved-timeline' component by reducing duplication, grouping related styles, and streamlining the structure.
> [#1097]: refactor improved-timeline scss

- src/components/molecules/article-status/article-status.scss
- src/components/molecules/article-status/article-status.tsx
- src/components/molecules/timeline/timeline.scss
Not an ideal solution, we should create a ticket to improve the CSS
> Article status on medium viewports

- src/pages/reviewed-preprints/[...path].page.tsx
part of elifesciences/enhanced-preprints-issues#1106
> refactor page props

- src/components/atoms/reference-list/reference-list.test.tsx
- src/components/atoms/reference/reference.scss
- src/components/atoms/reference/reference.test.tsx
- src/components/atoms/reference/reference.tsx
as part of the work for this ticket: https://github.com/orgs/elifesciences/projects/11/views/4?pane=issue&itemId=88326567&issue=elifesciences%7Cenhanced-preprints-issues%7C1213
users will be a able to click on the reference title and navigate to the material in question
> Add url to references

- src/components/atoms/reference/reference.scss
- src/components/atoms/reference/reference.stories.tsx
- src/components/atoms/reference/reference.test.tsx
- src/components/atoms/reference/reference.tsx
- src/types/reference.ts
https://github.com/elifesciences/enhanced-preprints-issues/issues/1243
> Add comments to the reference if they are present
