src/components/atoms/title/title.test.tsx

tsc could not resolve types in the title tests so they have been specified to allow the build to run

specify types in test where inference fails

---

src/components/atoms/article-content/article-content.stories.tsx
src/components/atoms/article-content/mock-content.ts
src/types/content.ts

Being explicit with the mockData const type showed some further issues with our typing:
- `ImageObject` has optional content and contentUrl properties
- `Link` has an optional relation property
We can now also remove @ts-ignore from `article-content.stories.tsx`
One for @will-byrne to review

Refine the content types based on the mockContent data.

---

src/utils/content-to-jsx.test.tsx
src/utils/content-to-jsx.tsx

Because it's quick and needed for launch (talked about in cross-functional discussion)

Fix citations needing to be in brackets

---

.storybook/fix-next-image.js
.storybook/preview.js
next.config.js
src/components/molecules/site-header/site-header.tsx
src/pages/[msid].page.tsx
src/pages/reviewed-preprints/[msid].page.tsx
src/setupTests.ts

To allow clean proxy behaviour, we tell nextjs to publish all content at `/reviewed-preprints`. We then change the main page route to be from the basePath so that /reviewed-preprints/12345 still resolves. 
~This change does mean `/` can no longer route from epp client and will result in a 404 or 5xx on the EPP system url (i.e. not through journal).~
I came up with a better way that redirects wayward requests to the correct place, and allows us to prefix assets in prod to the journal Url. 
This whole journal integration will need a look at again after launch, but this will at least work in a non-journal specific way.

Fix routing for journal proxying

---

src/components/atoms/investors/investors.tsx

The sizes set in the next/image object are for producing optimized images for mobile and HiDPI screens. This needs to be the target height for display in page - what we want it to be.
This PR sets the next/image component width/height at the appropriate ratio adjusted width in ratio to the height set by other logos. This fixes issues with oversized images rendering when there is a CSS failure.

fix the size of funder images 

---

docker-compose.yaml

fix: node_modules volume doesn't get repopulated on first boot, and also can get stale. run 'yarn' with node_modules mounted to repopulate on every startup.
This caused hard to diagnose differences between local and prod

fix docker-compose: run 'yarn' with node_modules mounted to repopulate on every startup

---

docker-compose.prod.yaml

I think this might also be a fix for @discodavey 's issue with running `make start-prod`. For me locally this resolves an issue waiting for the app service to be healthy.

fix healthcheck when running in prod-mode as the build needs more time than a dev server run

---

src/pages/_app.page.tsx
src/pages/_document.page.tsx

```
Warning: <title> should not be used in _document.js's <Head>. https://nextjs.org/docs/messages/no-document-title
```

fix issue with placement of next/title prerendering in the wrong place

---

src/utils/json-fetch.ts

I added this locally when I hit an issue and I needed to know which of the fetches was failing.

Improve error logging during jsonFetch

---

src/components/pages/article/article-page.module.scss

moving padding and margin broke width on small devices

fix tabbed navigation issue.

---

src/components/atoms/modal/modal.scss
src/components/atoms/modal/modal.stories.tsx
src/components/atoms/modal/modal.test.tsx
src/components/atoms/modal/modal.tsx

This progresses the modal component in the following ways:
- improves the styling to ensure that the close button is inline with the title matching designs.
- ensures that there is no trigger for opening the modal within the modal component but provides an example (with tests) on how the trigger behaviour can be assigned to an element in the DOM.
- will simplify the [PR for the share modal](https://github.com/elifesciences/enhanced-preprints-client/pull/310)

Refactor modal to improve styles and remove trigger from template

---

.github/workflows/build-preview.yaml

We recently switch the env build script to post the latest digest instead of relying on the commit hash, and to check for pr_id tag name This switches the image tag to be pr_id, which:
- reduces the number of tags in the CR view
- allows for there to not be a flip/flop when checking for the latest image (we just update the digest instead)
- pr_id is slightly more consistent that the sha, as that changes with pushes to master (without triggering the build).
Finally, we stall the pipeline for 30 mins waiting for the Environment to appear before we publish the Preview Environment. This should also make the developer experience slightly better, rather than having to infer and wait after the env URL is posted.

Start building images tagged with pr_id, and only post Preview URL if  detected 200 status code

---

.dockerignore
Dockerfile

The EPP client container is one of the biggest on the cluster, taking up 3.2GB. To make matters worse - we deploy most of that again for the storybook container.
We can reduce the size considerably by simply ignore newly added data files, and building node_modules in a separate build step and only copying the output

Slim down the EPP-client container

---

.eslintrc.js
package.json
src/pages/_document.page.tsx
src/utils/content-to-jsx.test.tsx
src/utils/content-to-jsx.tsx
yarn.lock

```
- warn The Next.js plugin was not detected in your ESLint configuration. See https://nextjs.org/docs/basic-features/eslint#migrating-existing-config
```
This PR "fixes" this.
It also fixes the one linting fail that resulted from this (though there are a few warnings too)

Add additional nextJS linting plugin

---

src/utils/content-to-jsx.test.tsx
src/utils/content-to-jsx.tsx

Needed before we upgrade to Encoda 1.0.0 but we should release shortly after upgrade.

Remove brackets from single Cite block

---

src/pages/_app.page.tsx
src/pages/_document.page.tsx

Currently broken in prod
Moved it to `_app.page.tsx` because it is not supported in next/head, and breaks if outside next/head in `MyApp` in `_document.page.tsx`

move next/script tags to _app

---

src/components/atoms/button/button.scss

if we wish to allow a default value of none it should not use the url()
see: https://stackoverflow.com/questions/1161061/css-background-image-urlnone-leading-to-errors-in-apache-log-file

fix: remove default value for background_image in button-icon mixin

---

README.md
docker-compose.yaml

This commit updates the docker-compose.yaml file to include fallbacks for the API_SERVER and MANUSCRIPT_CONFIG_FILE environment variables. It also updates the README.md file with instructions on how to recreate an issue experienced in production.

feat: Add environment variable fallbacks and documentation

---

src/types/reference.ts
src/utils/mocks/references.ts

This commit modifies the structure of the Publication type to accept a string or number for volumeNumber, and updates the mock references accordingly.

feat: Allow string input for volumeNumber in Publication type

---

browser-tests/api-reviewed-preprints.spec.ts
src/pages/api/reviewed-preprints.page.test.ts
src/pages/api/reviewed-preprints.page.ts
src/pages/api/reviewed-preprints/[msid].page.ts

The `prepareAuthor` function from `reviewed-preprints.page.ts` is now exportable. It is imported and utilized in `reviewed-preprints/[msid].page.ts` to prepare the authors' metadata.

feat: make prepareAuthor function exportable and use it in [msid].page.ts

---

src/pages/api/reviewed-preprints.page.test.ts
src/pages/api/reviewed-preprints.page.ts
src/pages/api/reviewed-preprints/[msid].page.ts
src/types/reviewed-preprint-snippet.ts

This commit updates the 'published' and 'reviewedDate' properties in the 'reviewedPreprintSnippet' function to use 'firstPublished' instead of 'published'. Also, it adds 'firstPublished' as a new property in the 'EnhancedArticleNoContent' type. Additionally, it changes the import path of 'Author' in the 'reviewed-preprints.page.test.ts' file.

feat: update 'published' and 'reviewedDate' to use 'firstPublished'

---

src/pages/api/reviewed-preprints.page.ts

This commit adds a function to convert Date objects into ISO strings without milliseconds. This function is then used to format the 'published', 'reviewedDate', 'versionDate', and 'statusDate' fields in the 'reviewedPreprintSnippet' function.

feat: add function to format date without milliseconds

---

.github/workflows/ci.yaml
docker-compose.browsertest.yaml

With a completely clean docker, you bring up the browser test setup by running `docker compose -f docker-compose.browsertest.yaml up` on it's own. It depends on a volume being filled by running `docker compose up` first.
This removes that dependency. Also separates it to another job which reduces overall CI time by about 45s

Remove superflous volume mounts that stop the browser tests running without having run the full suite beforehand

---

.github/workflows/chromatic.yaml
src/utils/mocks/content.ts

This change means that if there are changes in need of approval, the job will exit with non-zero. In other words - changes in need of approval fail the build.
The workflow for a failing commit to be approved then is:
- action run test job, fails
- follow the status to review and approve
- rerun the failing job.
With this change, we can now consider integrating with the ci workflow to stop the build on chromatic failure

use exitZeroOnChanges option to fail a job on unapproved changes

---

yarn.lock

Replicated the change [here](https://github.com/elifesciences/enhanced-preprints-client/pull/1975) without the weird odd issue with accessing chromatic token

Bump braces from 3.0.2 to 3.0.3

---

yarn.lock

Recreate [this PR](https://github.com/elifesciences/enhanced-preprints-client/pull/1994) to work around dependabot and secrets issue

Bump ws from 8.13.0 to 8.18.0

---

docker-compose.prod.yaml

When using prod mode, it becomes impossible to test what happens in the real scenario that:
- the next build is run without any environment/config
- the server is started with environment/config
With this change we can run `yarn build` in your checkout, without config, and then restart the app (`docker compose restart app`) to see the effects
Used and testing during https://github.com/elifesciences/enhanced-preprints-client/pull/2165

Improve prod mode for changing global config between build and server start

---

src/components/atoms/reference-list/reference-list.scss
src/components/atoms/reference-list/reference-list.test.tsx
src/components/atoms/reference-list/reference-list.tsx
src/components/atoms/reference/reference.scss
src/components/atoms/reference/reference.stories.tsx
src/components/atoms/reference/reference.test.tsx
src/components/atoms/reference/reference.tsx

This purpose of this branch is to refactor the references and reference-list components to remove the coupling between the two. The styling in particular is in particular very closely coupled and some of the styles for the reference were only coming from reference-list.

References refactor

---

src/components/atoms/reference-list/reference-list.test.tsx
src/components/atoms/reference/reference.test.tsx
src/components/atoms/reference/reference.tsx
src/utils/mocks/references.ts

related to this issue: https://github.com/orgs/elifesciences/projects/11/views/4?pane=issue&itemId=38344522&issue=elifesciences%7Cenhanced-preprints-issues%7C815

make meta.yearPulished the default reference year value
